[package]
name = "scrying"
version = "0.8.0"
authors = ["David Young <david.young@nccgroup.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "A new tool for collecting RDP, web and VNC screenshots all in one place"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
# pending https://github.com/clap-rs/clap/issues/1965 making a release
clap = "3.0.0-beta.2"
#clap = { git = "https://github.com/clap-rs/clap", rev = "8145717" }
rdp-rs = "0.1.0"
image = "0.23.4"
simplelog = "0.8"
log = "0.4.8"
thiserror = "1.0"
url = "2.1.1"
nmap_xml_parser = { "git" = "https://github.com/Ayrx/nmap_xml_parser" }
headless_chrome = { "git" = "https://github.com/jeprojects/rust-headless-chrome", "rev" = "c4bb66a1" }
failure = "0.1"
askama = "0.10"
socks = "0.3"
vnc = "0.4"
nessus_xml_parser = "0.1"
ctrlc = "3.1"

[package.metadata.deb]
depends = "chromium"
extended-description = """\
A new tool for collecting RDP, web and VNC screenshots all in one place\
"""
section = "net"
priority = "optional"
assets = [
	["target/release/scrying", "usr/bin/", "755"]
]
